### ISSUE TITLE
OsDev Italia 

### ISSUE THREAD

**Issue by ghost** [davidepianca98/hoho-os#1]
Ciao!
Il mio nome è Nicolò e sono uno dello staff di OsDev italia. OsDev è una community ovviamente aperta a tutti Quelli che sviluppano un sistema operativo da zero. Penso che tu sia già andato sul forum/wiki inglese, ecco noi abbiamo aperto la community italiana per gli amanti dello sviluppo. Questa community è aperta da un po di anni e siamo sempre alla ricerca di eventuali OS tutti made in italy.
Attualmente il sito è poco aggiornato (infatti stiamo facendo modifiche interne poi rilasceremo alcune news) ma ti lascio il link: http://www.osdev.it 
Nel nostro blog esiste una serie di articoli dove commentiamo appunto OS Italiani, dopo 3 anni di nessuna notizia volevamo riaprire la serie con il Tuo OS. Sarei felice se rilascia una release o comunque se mi raccontasse qualcosa di più su di te e il tuo OS. Sono disponibile per ulteriori informazioni

**Comment by davidepianca98** [comment]
Ciao! 
Grazie mille per l'interesse in questo mio progetto, purtroppo non sono riuscito a svilupparlo per vari mesi, ma adesso ho ripreso e mi sto occupando a portare gcc e a creare un editor di testo in modo da poter essere indipendente dall'esterno. Mancano ancora varie funzioni, soprattutto le system call sono ancora ridotte ma ci sto lavorando, inoltre devo migliorare la documentazione. Una release di un OS effettivamente utile è ancora lontana, ma le funzioni base ci sono e le sto allargando.

**Comment by ghost** [comment]
Grazie per la sua velocità! L'ho compilato e devo dire che è veramente bello. Ti consiglio una release perché così puoi tracciare i tuoi obiettivi ad esempio nella prima hai solo il bootloader la seconda la shell...
Volevo tanto recensirlo

**Comment by davidepianca98** [comment]
Sì, potrei fare una release ma prima avevo comunque intenzione di migliorare alcune cose che non sono gestite nel migliore dei modi. Se vuole recensirlo io sarei molto contento, questa sera comunque credo di aggiornarlo ancora

**Comment by ghost** [comment]
Sarei molto felice se lei Volesse iscriversi sul nostro forum per discutere e ovviamente pubblicizzare il suo OS. Grazie per l'attenzione. 
Ps: visto che non ho sotto mano il PC perennemente per compilare il suo OS potrebbe inviarmi una iso o qualcosa del genere quando ha finito?

**Comment by davidepianca98** [comment]
Certamente, vedrò di iscrivermi e magari carico anche un'iso appena possibile e la avverto. Scriverò anche delle istruzioni su come utilizzarlo con VirtualBox in modo ottimale nel Readme

**Comment by ghost** [comment]
Perfetto! Allora ci si sente sul forum. Intanto ti auguro una buona serata
